### ISSUE TITLE
Merge request forms

### ISSUE THREAD

**Issue by veksen** [the-programmers-hangout/website#104]
We currently have a separate website that offer forms to copy/paste formatted content for #hire-me etc. I think the the websites should be merged.

**Comment by aerori** [comment]
**General page/input box spec implementation plans:**
Add a forms link to the sidebar footer and create links for the forms.

Headings: h5 (montserrat 23.75) - currently conflicted on whether h5 or h6 (or even smaller) looks better. Need a mockup to figure it out.
Text sizing: kb-sidebar L1 (oxygen 24 unbolded)
Inside input boxes (maybe): standard body size (oxygen 18)
Standard width: 880x40, 5px radius (probably needs to be smaller ->2,3px)

The spacing between the input heading and the box is 8px. Input text is centered within box with a padding of 16px from the left

Theme specific styling-
**Light theme:**
bg: #ffffff
input bg: #EAEAEA
text: #000000
filler text: #656565

**Dark theme:**
bg: #1F2A34
input bg: #344149
text: #ffffff
filler text: #CFD9E3 (check if it's 2a on bg- if it's not 2a but the ratio is fairly close to 4.5 then it's ok for now)

**Comment by aerori** [comment]
figma link: https://www.figma.com/file/7W7iK9XhSPG0aCFLg2CAVN/tph-forms?node-id=2%3A9

**Comment by veksen** [comment]
Can the placeholder and text have a bigger difference? It's a little too subtle

Also active input?

**Comment by aerori** [comment]
updated that in the forms.

**Comment by veksen** [comment]
superseeded by https://github.com/the-programmers-hangout/website/issues/364
