### ISSUE TITLE
Home: fix svg waves across resolutions

### ISSUE THREAD

**Issue by veksen** [the-programmers-hangout/website#110]
Find a better way to implement the waves across resolutions.

Possibly catalogue the homepage across common resolutions on Figma to get a "best case scenario".

bad: 2560x1440 @ 2560x955 body

**Comment by Moe-Szyslak** [comment]
I've noticed that there seems to be an extra path on the bottom wave svg that isn't needed and causes the strange curve

screenshot before
![image](https://user-images.githubusercontent.com/34754130/70869517-b1a85f80-1f83-11ea-9ff4-d6833c687d6f.png)

screenshot after deleting `url(#bot_gradient5)` from the bottom wave svg
![image](https://user-images.githubusercontent.com/34754130/70869687-05b34400-1f84-11ea-8a52-eaf79f277a7a.png)


May also be related but on both images there's a small gap at the bottom that is missing colours

this is all at 2560x1440 @ 2560x981 body

**Comment by veksen** [comment]
@Moe-Szyslak that's actually a very good fix!

You're free to do a PR, otherwise I can do it

**Comment by puremana** [comment]
I think you can close this issue now
