### ISSUE TITLE
404: better handled + design

### ISSUE THREAD

**Issue by veksen** [the-programmers-hangout/website#120]
Hitting a 404 from anywhere will trigger the page below:

Things that would be nice:

- Separate resources 404 from generic 404 (inspired from https://www.gatsbyjs.org/docs/creating-prefixed-404-pages-for-different-languages/ same concept as us)
- Suggest a set of probable wanted pages via Levenshtein

Let's also make it pretty.

![image](https://user-images.githubusercontent.com/3461986/66450059-22337d00-ea25-11e9-9f9e-b2cf038c8789.png)

**Comment by ThePicoNerd** [comment]
Is this issue still alive?

**Comment by veksen** [comment]
Yes

**Comment by kkhan01** [comment]
Hey, it didn't seem like this issue's sub directory aspect isn't  being addressed in PR https://github.com/the-programmers-hangout/website/pull/126.

I'd like to attempt and work on this issue. If anyone else is interested, they should check out [my fork](https://github.com/kkhan01/website/tree/resources-404) to work together so no one does any redundant work.
