### ISSUE TITLE
Add JetBrains logo + mention in the home page

### ISSUE THREAD

**Issue by veksen** [the-programmers-hangout/website#127]

**Comment by supergrecko** [comment]
What's the status on this issue? Is it up for grabs or are you planning on doing it? (Asking becase you self-assigned)

**Comment by veksen** [comment]
I have the design in the mockups, I need to implement it. Self assigned because it's pretty specific.

**Comment by veksen** [comment]
Blocking a first release because of our relationship with JetBrains
