### ISSUE TITLE
Resources: enforce order of languages

### ISSUE THREAD

**Issue by veksen** [the-programmers-hangout/website#140]
The order is random right now, I'm not sure where the issue is:

<table>
<tr>
<td>
<img src="https://user-images.githubusercontent.com/3461986/66464212-8b7ab680-ea4c-11e9-9f0d-20abb72cdad0.png" />
</td>
<td>
<img src="https://user-images.githubusercontent.com/3461986/66464224-92a1c480-ea4c-11e9-9346-a46c2796c903.png" />
</td>
</tr>
</table>

**Comment by sanketmaru** [comment]
I would be happy to contribute to this project and help to fix this issue.

**Comment by veksen** [comment]
That would be great!

**Comment by sanketmaru** [comment]
Please assign me. Will start on it

**Comment by veksen** [comment]
Feel free to start and open the PR, as per open source we don't directly assign issues to people aside from very direct contributors :)
