### ISSUE TITLE
Resources: very long links and wide images break mobile

### ISSUE THREAD

**Issue by veksen** [the-programmers-hangout/website#143]
Must limit image width inside markdown component, and most likely word-wrap the links.

![](https://media.discordapp.net/attachments/244230771232079873/632056840888385558/Screenshot_20191010-232804_Chrome.jpg)

**Comment by mrneo240** [comment]
I hereby Grant give the owners of this repo a perpetual license to use this Image.

**Comment by adin234** [comment]
[PR](https://github.com/the-programmers-hangout/website/pull/150) Created
