### ISSUE TITLE
Bug: Profile pictures break on articles when users change them

### ISSUE THREAD

**Issue by Hamzantal** [the-programmers-hangout/website#146]
https://theprogrammershangout.com/resources/kotlin/native/creating-c-bindings.md

Profile picture does not load up for me ^^

**Comment by Hamzantal** [comment]
Is the discord cdn's link to the profile picture also removed after it is changed?

**Comment by Phoenix181** [comment]
We could use Discord API to retrieve the profile picture from their Discord Tag or ID?

**Comment by veksen** [comment]
We're now creating a nightly build which refetches the user avatars. This should be good enough!
