### ISSUE TITLE
Ongoing design work

### ISSUE THREAD

**Issue by veksen** [the-programmers-hangout/website#15]
Figma file visible here: https://www.figma.com/file/Yz2t51GRnlcPPRujlTj3ggLl/tph-sketch?node-id=0%3A1&viewport=-774%2C487%2C0.5131944417953491

Note to anybody wanting to contribute:
We are not done with the design, avoid opening a design-related PR for the time being. (Especially true with the rebranding). A clean up is being done in #64.

Also meta issues can be found in #64.

**Comment by aerori** [comment]
added a dark scheme.
![about page](https://user-images.githubusercontent.com/31824839/62133335-9c6cb600-b2ac-11e9-99cb-c7563a830ef0.png)
![docs](https://user-images.githubusercontent.com/31824839/62133383-aabad200-b2ac-11e9-8140-fb15d2362c97.png)

**Comment by veksen** [comment]
See #64.
