### ISSUE TITLE
Bug: Broken profile picture on arrow functions article

### ISSUE THREAD

**Issue by T0MGithub** [the-programmers-hangout/website#151]
https://theprogrammershangout.com/resources/javascript/es6/arrow-functions.md

I haven't changed my profile picture, which apparently breaks the profile picture, as seen in #146.

I think it is because my tag is listed as "t0m#5956" on the article as apposed to what it actually is "T0M#5956".

**Comment by supergrecko** [comment]
Discord tags are case sensitive so you need the right tag on it.

If this is not the cause then it's probably #146

**Comment by T0MGithub** [comment]
![image](https://user-images.githubusercontent.com/47010185/67158134-16e92700-f32c-11e9-8948-5d71ef967ec7.png)
^ the tag is "t0m#5956"

In the document it is listed as "t0m#5956".

I haven't changed my profile picture.
