### ISSUE TITLE
Find a name for the docs

### ISSUE THREAD

**Issue by veksen** [the-programmers-hangout/website#16]
It's currently used as "Docs", but I don't think it's quite right. "Knowledge base" comes to mind, open to suggestions.

To put in perspective, our vision is to offer articles or longer explanations on some languages/topics, mainly those frequently discussed concepts.

**Comment by Xetera** [comment]
I think "resources" would be pretty short and explanatory.

**Comment by 1Computer1** [comment]
How about:
- Guides
- Articles
- Encyclopedia

Maybe something more verbose to make it stand out, like "Explanations of Concepts".

**Comment by eslachance** [comment]
There are a vast majority of names that could be had, none that really covers all use cases. Documentation, Reference, Guides, Tutorials, How-Tos, Articles (knowledge base).... all these things have different meanings and different purposes. Documentation and Reference gives you the "how", Guides and Articles are usually about the "what" and sometimes about the "why". 

So I wouldn't go for a single umbrella term, but rather decide if those should be separated and populated with various sources.

**Comment by veksen** [comment]
Using Resources for now, will explore, we think it has a closer meaning to what we want to use it for. This is easy to change, and we're very open to change it.

**Comment by resynth1943** [comment]
call it TPHIS

**Comment by supergrecko** [comment]
> call it TPHIS

Any specific reason? More context?

**Comment by resynth1943** [comment]
It's a joke that would fit poorly here, but the first three letters are The Programming Hub
