### ISSUE TITLE
Add responsive title to the misc. pages

### ISSUE THREAD

**Issue by Dreameh** [the-programmers-hangout/website#167]
Add 
```
    @media screen and (max-width: 991px) {
      font-size: 58px;
    }
    @media screen and (max-width: 767px) {
      font-size: 32px;
    }
```
to [this](https://github.com/the-programmers-hangout/website/blob/master/src/components/Header/styles.tsx#L22) in order to not break the page when loading the miscellaneous pages like rules and the about page.

**Comment by veksen** [comment]
This is a little bit more than this, because h1/h6 are generated via a modular scale. What do you mean by "breaking the page"?

**Comment by Dreameh** [comment]
![Screenshot_20191120-202525](https://user-images.githubusercontent.com/9027391/69266811-92acec80-0bd4-11ea-9cf3-1483f1f7833a.jpg)
![Screenshot_20191120-202530](https://user-images.githubusercontent.com/9027391/69266812-92acec80-0bd4-11ea-9b24-840cfad747f4.jpg)

This is what I am talking about, and this happens on every single phone browser. It breaks the page in a way where the whole title takes too much space and once you swipe the page a little, you notice that it will have a extra space for it.

The modular scale does not work on Titles.

**Comment by veksen** [comment]
ty!

**Comment by veksen** [comment]
This is a lot better at the moment, still open to look at this more if more phone size are problematic!

**Comment by Dreameh** [comment]
I would say that it's working just fine now as the size of the title is no longer problematic, which was the main cause to why it was borked in the first place.

I tried to see if anything was wrong through my phone and the browsers developer tools, but I couldn't find any which relates to this issue.

if it becomes problematic in the future, then perhaps a em/rem approach would probably be better.
