### ISSUE TITLE
Long code blocks causing unresponsive design

### ISSUE THREAD

**Issue by LBlend** [the-programmers-hangout/website#170]
## What is the issue?
Long code blocks cause certain elements of some pages to be unresponsive. This is especially prevalent on mobile devices due to the screen resolution typically being lower than on desktop devices.

## Examples
All of the examples below are from the [what is docker](https://theprogrammershangout.com/archives/what-is-docker.md) page though, I've also experienced elsewhere, like the [what is graphql](https://theprogrammershangout.com/archives/what-is-graphql.md) page.

![image](https://user-images.githubusercontent.com/24893890/69256712-30df8900-0bba-11ea-8b8a-2829c689368c.png)
## 
![image](https://user-images.githubusercontent.com/24893890/69257679-c29bc600-0bbb-11ea-8870-cce4008bc141.png)

## 
This issue also may occur on desktop depending on the browser zoom level, OS scaling settings, screen resolution and font size:
![image](https://user-images.githubusercontent.com/24893890/69255434-1ad0c900-0bb8-11ea-902b-839052c60092.png)

##
[Here's a video demontration](https://streamable.com/cukyi)

**Comment by veksen** [comment]
This particular article needs to be updated to use an actual codeblock, and not inline code. Code block will scroll properly.

Nonetheless the long inline code needs to be fixed, as well.
