### ISSUE TITLE
Dark/Light mode glitch

### ISSUE THREAD

**Issue by atomic404** [the-programmers-hangout/website#194]
![Glitch Information GIF](https://user-images.githubusercontent.com/56467468/70730707-c37ccf00-1d05-11ea-8fab-498d11148aad.gif)

basically when we are on light mode, and refresh the page, the css sets itself to dark mode, but u can still click "Switch to dark mode"

**Comment by atomic404** [comment]
Ignore the facebook bookmark :KEKW: i just installed chrome again.. :joy:

**Comment by NevilleMthw** [comment]
I don't know if this is related or not, but I changed to light mode and went back to the homepage, resources and tech spotlight tabs are basically impossible to see unless you hover over them. Just an accessibility issue I guess.

**Comment by matthewwolfe** [comment]
![bug](https://user-images.githubusercontent.com/2324850/87862804-03520780-c922-11ea-99f8-ea0463bffd63.gif)

When I refresh, I always get dark mode even if light mode is selected and saved in local storage. This does not happen in the local dev build (it works correctly there)

**Comment by travisk-codes** [comment]
Has this issue been resolved? Don't think I can reproduce.

**Comment by veksen** [comment]
nothing has changed that would fix it (aside from lib updates). I had a lot trouble reproducing, seen it a few times but without luck to find the cause.

**Comment by veksen** [comment]
Duplicate to https://github.com/the-programmers-hangout/website/issues/334 documented there and an idea with how to fix
