### ISSUE TITLE
Move from MD to MDX

### ISSUE THREAD

**Issue by veksen** [the-programmers-hangout/website#250]
This supports https://github.com/the-programmers-hangout/website/issues/232 and allows stuff like attaching Youtube videos (https://fionawh.im/blog/2019/09/fast-youtube-embed/), or just custom components for rendering code blocks (maybe multi language, etc, like: https://github.com/the-programmers-hangout/website/issues/48)

https://www.gatsbyjs.org/docs/mdx/getting-started/
https://www.gatsbyjs.org/packages/gatsby-plugin-mdx/
https://www.freecodecamp.org/news/convert-the-gatsby-default-starter-blog-to-use-mdx/

**Comment by dfireBird** [comment]
The plugin changes some fields names and removes some of them can I also change/remove it from `generated/grapql.ts`?

**Comment by veksen** [comment]
closed by #286
