### ISSUE TITLE
Incorporating AMAs

### ISSUE THREAD

**Issue by kkhan01** [the-programmers-hangout/website#251]
Currently, our AMAs live [here](https://the-programmers-hangout.github.io/ama-archive/), which is detached from the main website. 

Several ways that come to mind to include: including it as a submodule since netlify has [this](https://docs.netlify.com/configure-builds/repo-permissions-linking/#git-submodules), using subtrees, just including it as-is into the repository (styling the index page).

**Comment by veksen** [comment]
see #245
