### ISSUE TITLE
Change "expand languages" to "expand resources" or "expand topics" to encompass misc. topics

### ISSUE THREAD

**Issue by TomPrograms** [the-programmers-hangout/website#254]
As seen in the screenshot below, resources are listed under the heading "expand languages" in the navigation sidebar, however the list contains more than just languages, such as "cryptography" and "bot-development". In order to make more sense the heading should be "expand resources" or "expand topics" or similar.

![screenshot of "expand languages" section](https://user-images.githubusercontent.com/47010185/82351326-5a0b9580-99f4-11ea-9ec9-de1ec32d95b6.png)

**Comment by veksen** [comment]
I'll expand on this, the ultimate goal is to split "topics" and "resources" into 2 different entities.
