### ISSUE TITLE
About page table of content selection indicator skips 3rd element

### ISSUE THREAD

**Issue by DarkEyeDragon** [the-programmers-hangout/website#288]
https://i.imgur.com/g4XM3qM.gif

the 3rd element gets skipped when scrolling through the page (even when clicking directly on the ToC link).
Most likely due to it being 1 line

**Comment by veksen** [comment]
Hey, I've seen the issue, sorry for the lack of feedback, I'm just not sure what would the behaviour should be then?

**Comment by DarkEyeDragon** [comment]
I'm honestly not sure. Idealy for it to not skip over, but I don't know how doable that is as its only one line. It's not a big deal really. Just wanted to point it out in case you could fix it.
