### ISSUE TITLE
Suggestion: Sidebar header style/colors

### ISSUE THREAD

**Issue by travisk-codes** [the-programmers-hangout/website#326]
Current:
![tph-header-before](https://user-images.githubusercontent.com/7794722/92267718-1d827d80-eeaf-11ea-9abc-451d11baba24.png)
Suggested:
![tph-header-after](https://user-images.githubusercontent.com/7794722/92267735-2410f500-eeaf-11ea-97e7-8c5b4e35b586.png)

**Comment by veksen** [comment]
Would look at this again after https://github.com/the-programmers-hangout/website/issues/347 is implemented and see how we feel
