### ISSUE TITLE
Add navigation buttons at the bottom of the page for related pages.

### ISSUE THREAD

**Issue by DracTheDino** [the-programmers-hangout/website#338]
At the bottom of certain pages, it could be easier to implement a navigation button which takes you to the next related document or the previous page. 
Example: the http-project guide. It seems unintuitive to open the nav bar to go to the next page so it would be super nice here.

**Comment by veksen** [comment]
Yes 100%.

What I'm thinking: Have the button navigate to either the next sibling (page), or the next directory.

**Comment by veksen** [comment]
Gatsby docs do it like this:

https://www.gatsbyjs.com/docs/quick-start/

![image](https://user-images.githubusercontent.com/3461986/93086184-ba3ddb80-f664-11ea-8a8c-1ce6374d0bfd.png)

**Comment by veksen** [comment]
I've prepared a simple design for it

![image](https://user-images.githubusercontent.com/3461986/93404179-88d93180-f857-11ea-9e69-0398203deba2.png)

**Comment by DracTheDino** [comment]
I don’t know anything about React or Gatsby but here goes my idea: in the Markdown file for each of the pages, we would add two new labels: `project_label` which would be the name of the project like “DIY HTTP Server” and `page_number` which would be a number. How I thought it would work is it would look for pages with the same label and add the links in an array which would be used to switch pages.

Let me know how this sounds and if it is possible.

**Comment by dfireBird** [comment]
@woojiahao has already implemented a similar paging system in his personal site! We can use that as reference.

[https://github.com/woojiahao/woojiahao.github.io](The repo) of the site.

If it's open to implement I can do it.

**Comment by veksen** [comment]
closed by #359
