### ISSUE TITLE
[Bug] Mobile resource header is off-center in Firefox

### ISSUE THREAD

**Issue by travisk-codes** [the-programmers-hangout/website#341]
**Description:** When you visit https://theprogrammershangout.com/resources with a mobile-width on Firefox, the resources text box is off-center (see screenshot)

**To Reproduce:**
1. Open Firefox
2. Navigate to https://theprogrammershangout.com/resources
3. Reduce/zoom page to mobile layout
4. Observe the resource header text box

**Expected Behavior:** For the box to be centered on the page.

**Environment:**
- OS: 5.8.6-arch1-1
- Browser: Firefox 80.0.1 (64-bit)
- Works on Chromium 85.0.4183.83 (64-bit)

![tph-reource-header](https://user-images.githubusercontent.com/7794722/93213375-c348ae80-f731-11ea-9004-cad471d8f95c.png)

**Comment by veksen** [comment]
`max-width: calc(100% - 96px)`

on `Box` should fix it
