### ISSUE TITLE
[Bug] Resource page link underlines don't follow text

### ISSUE THREAD

**Issue by travisk-codes** [the-programmers-hangout/website#346]
**Description:** Links at the bottom of resource pages that span more than one line only have an underline for the last line, and it expands past the text (see screenshot)

**To Reproduce:**
1. Navigate to a resource page with links at the end (e.g. https://theprogrammershangout.com/archives/what-is-julia.md)
2. Scroll to bottom of the page where links are located
3. Observe a long link

**Expected Behavior:** For the link underline to be under the entire link and not extend past the text

**Environment:**
- OS: 5.8.6-arch1-1
- Browser: Firefox 80.0.1 (64-bit)
- Browser: Chromium 85.0.4183.83 (64-bit)

**Screenshots:**
![tph-resource-links](https://user-images.githubusercontent.com/7794722/93533749-99e67900-f911-11ea-9a62-22c61b1a89f1.png)
![tph-resource-links-2](https://user-images.githubusercontent.com/7794722/93533763-a36fe100-f911-11ea-9be8-b05ab36c7c23.png)

**Comment by veksen** [comment]
Leaving this codepen here: those were my attempts at solving this, I couldn't crack it.

https://codepen.io/veksen/pen/YzyZzNV
