### ISSUE TITLE
Design dark mode

### ISSUE THREAD

**Issue by veksen** [the-programmers-hangout/website#35]
Yeah

**Comment by Moe-Szyslak** [comment]
In terms of multiple themes for the site - might be interesting to allow custom values for this. Similar to how an IDE handles it. Could be stored in localstorage or eventually in a DB.

Failing that may I suggest the following colour theme

Hex       | RGB           | HSL             | ![Color Picker Boxes](https://draculatheme.com/assets/img/color-boxes/eyedropper.png)
---       | ---           | ---             | ---
`#282a36` | `40 42 54`    | `231° 15% 18%`  | ![Background Color](https://draculatheme.com/assets/img/color-boxes/background.png)
`#44475a` | `68 71 90`    | `232° 14% 31%`  | ![Current Line Color](https://draculatheme.com/assets/img/color-boxes/current_line.png)
`#44475a` | `68 71 90`    | `232° 14% 31%`  | ![Selection Color](https://draculatheme.com/assets/img/color-boxes/selection.png)
`#f8f8f2` | `248 248 242` | `60° 30% 96%`   | ![Foreground Color](https://draculatheme.com/assets/img/color-boxes/foreground.png)
`#6272a4` | `98 114 164`  | `225° 27% 51%`  | ![Comment Color](https://draculatheme.com/assets/img/color-boxes/comment.png)

**Comment by aerori** [comment]
We _have_ a darkmode. I made it. Smh. @Moe-Szyslak I can try implementing a dracula scheme if you wanted.

**Comment by veksen** [comment]
I think we can consider this "done"?

I could see work done to tweak the scheme, unless this was about the code highlighting (is this what @Moe-Szyslak meant?)
