### ISSUE TITLE
[Design] Move Table of Contents from the bottom to the top of the page

### ISSUE THREAD

**Issue by DracTheDino** [the-programmers-hangout/website#365]
I feel that the table of content which is right at the bottom of each page could be moved up to the top of the page directly below the heading of the page. Just below this, I’ve attached an image of the [Rules](https://theprogrammershangout.com/rules) page as an example and I’ve scribbled a white line just below the heading, where I feel that the Table of Contents should be. 

![F5E00274-2965-430F-AE61-BE4BF65ED01A](https://user-images.githubusercontent.com/46294577/95006003-b6c2c200-061c-11eb-9f60-c6042daa0cae.jpeg)

I feel this would make navigating the page easier, if by chance I wanted to jump to a specific part of the page.

**Comment by veksen** [comment]
I agree, and could be a pretty easy task for someone to take!

**Comment by dfireBird** [comment]
The issue of Table of Contents being at the bottom is been there like forever. I thought I fixed that in PR #356! But it's still persists in widths between 768px and 1200px. Is that by choice or an issue?

**Comment by DracTheDino** [comment]
Done!
