### ISSUE TITLE
Create custom support for syntax highlighting .env files for prism

### ISSUE THREAD

**Issue by veksen** [the-programmers-hangout/website#367]
`.env` files are a simple key value delimited by `=`:

A regex would be: `/^\s*([\w.-]+)\s*=\s*(.*)?\s*$/`

Could look at https://github.com/PrismJS/prism/blob/master/components/prism-erb.js for implementation example, and then imported at the top of this file: https://github.com/the-programmers-hangout/website/blob/master/src/components/Markdown/index.tsx.

**Comment by ilitr** [comment]
I can work on this if no one shows interest.

**Comment by Mahamed-Belkheir** [comment]
can I be assigned to this?
