### ISSUE TITLE
Text overflows past viewport and background changes

### ISSUE THREAD

**Issue by norogoth** [the-programmers-hangout/website#412]
Here is what I see when I scroll towards the right on an article.

![2021-07-02_09-26](https://user-images.githubusercontent.com/52639031/124303768-ac841480-db17-11eb-9c55-e4ebacd28d2c.png)

I am trying to find the stylesheet to edit this document and I am unsure what to edit for this. This may be due to an unfamiliarity with Gatsby. But I would think there is a stylesheet to override Gatsby or other libraries.

![2021-07-02_09-25](https://user-images.githubusercontent.com/52639031/124303762-ab52e780-db17-11eb-9002-27f1270ba141.png)

At any rate, I think one of these container elements may be responsible for this issue.
![2021-07-02_09-29](https://user-images.githubusercontent.com/52639031/124304149-2caa7a00-db18-11eb-9258-447f3f14c035.png)

I am attempting to contribute to open-source projects for the first time, if any of my approach needs more clarification please let me know so I can improve my approach in the future.

**Comment by Xetera** [comment]
https://theprogrammershangout.com/archives/what-is-emacs.md here's an example of this bug
