### ISSUE TITLE
Feature request: Adding anchors to the different sections of a post

### ISSUE THREAD

**Issue by Aiden01** [the-programmers-hangout/website#61]
It would be nice if we were able to link to a specific part of a post. E.g:
![2019-08-14_12-39](https://user-images.githubusercontent.com/34129960/63039192-c61f0300-be90-11e9-8355-2d87aa135b62.png)

**Comment by veksen** [comment]
Theorically it should be possible if Markdown lets us write raw HTML (like Github flavoured markdown). Gotta double check. Then h1-6 with ids would need a specific style to note the anchor. I'll explore the idea.

**Comment by supergrecko** [comment]
We should be able to embed HTML via markdown with https://github.com/mdx-js/mdx if Gatsby does not support it out of the box.

**Comment by Aiden01** [comment]
Looks like there's a [plugin](https://www.gatsbyjs.org/packages/gatsby-remark-autolink-headers/) for that.
