### ISSUE TITLE
Resources: Python content

### ISSUE THREAD

**Issue by veksen** [the-programmers-hangout/website#90]

**Comment by izzergh** [comment]
Howdy, I am doing Hacktoberfest and I know a pretty good python! What kind of content did you want?

I noticed the **basics** placeholder. Is that something you would just want fleshed out? 

In general, I can write an article or two like:

* "basics": syntax; declaration of variables, functions, and classes; running a python program from the command line
* something weird and specific, like what decorators are and how to use them
* a list of links to existing articles or sites

Which of these would you prefer? Or did you have another idea?

**Comment by veksen** [comment]
I'm so sorry for the delay, and recognize Hacktoberfest is now over! If you are still wishing to contribute, we are first looking at articles that cover very commonly answered questions in specific language channels. So, if you're active in #python, this should give you a good idea on what is constantly being repeated, and which may need more details. The article doesn't need to be in depth, but at least, explain the concepts, while linking to related articles.

**Comment by izzergh** [comment]
Sure! I'll pop my head into the discord sometime this weekend.

**Comment by bobisageek** [comment]
Can I suggest that as the python content is being worked on, review and revise the content that's up there now. For example, the `Operators` page under python is incomplete (e.g. parens for grouping aren't mentioned) and inaccurate (the operator precedence table, for example, groups some sets of operators that aren't actually grouped). Might be a good exercise for someone who is detail-oriented and wants to get more familiar with operator precedences.

**Comment by itsneelpatel** [comment]
Hi, can you elaborate on what needs to be done here? 
Thanks.

**Comment by Xetera** [comment]
This issue is too broad. If you're interested in adding new content please discuss the specifics in the Discord server and let's turn this into a more attainable/measurable task that can be worked on.
